kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: development-pull-images
  namespace: cicd
subjects:
- kind: ServiceAccount
  name: default
  namespace: development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'