resources:
- argocd-admin.yaml
- ../base
- env-ops-configmap.yaml
- r-d0e902/configmap.yaml


patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r-d0e902/revision-patch.yaml
  target:
    kind: Service
- path: r-d0e902/routing-patch.yaml
  target:
    kind: Service