resources:
- ../base
- env-ops-configmap.yaml
- r-7b49bb/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r-7b49bb/revision-patch.yaml
  target:
    kind: Service
- path: r-7b49bb/routing-patch.yaml
  target:
    kind: Service