resources:
- ../base
- namespace.yaml
- env-ops-configmap.yaml
- r-e3ff76/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r-e3ff76/revision-patch.yaml
  target:
    kind: Service
- path: r-e3ff76/routing-patch.yaml
  target:
    kind: Service