resources:
- ../base
- namespace.yaml
- env-ops-configmap.yaml
- r-e1fc0c/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r-e1fc0c/revision-patch.yaml
  target:
    kind: Service
- path: r-e1fc0c/routing-patch.yaml
  target:
    kind: Service