apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-hello-world-config
  namespace: openshift-gitops
spec:
  destination:
    namespace: development
    server: 'https://kubernetes.default.svc'
  project: knative-app
  source:
    path: config
    repoURL: https://github.com/marrober/quarkus-hello-world-deployment.git
    targetRevision: main
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=true # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
    - CreateNamespace=false # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    retry:
      limit: 1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 20s # the maximum amount of time allowed for the backoff strategy
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-hello-world-development
  namespace: openshift-gitops
spec:
  destination:
    namespace: development
    server: 'https://kubernetes.default.svc'
  project: knative-app
  source:
    path: development
    repoURL: https://github.com/marrober/quarkus-hello-world-deployment.git
    targetRevision: main
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=true # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
    - CreateNamespace=false # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    retry:
      limit: 1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 20s # the maximum amount of time allowed for the backoff strategy
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: quarkus-hello-world-staging
#  namespace: openshift-gitops
#spec:
#  destination:
#    namespace: staging
#    server: 'https://kubernetes.default.svc'
#  project: knative-app
#  source:
#    path: staging
#    repoURL: https://github.com/marrober/quarkus-hello-world-deployment.git
#    targetRevision: main
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: quarkus-hello-world-production
#  namespace: openshift-gitops
#spec:
#  destination:
#    namespace: production
#    server: 'https://kubernetes.default.svc'
#  project: https://kubernetes.default.svc
#  source:
#    path: production
#    repoURL: https://github.com/marrober/quarkus-hello-world-deployment.git
#    targetRevision: main