apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-hello-world-config
  namespace: openshift-gitops
spec:
  destination:
    namespace: development
    server: 'https://kubernetes.default.svc'
  project: knative-app
  source:
    path: config
    repoURL: https://github.com/marrober/quarkus-hello-world-deployment.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-hello-world-development
  namespace: openshift-gitops
spec:
  destination:
    namespace: development
    server: 'https://kubernetes.default.svc'
  project: knative-app
  source:
    path: development
    repoURL: https://github.com/marrober/quarkus-hello-world-deployment.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: quarkus-hello-world-staging
#  namespace: openshift-gitops
#spec:
#  destination:
#    namespace: staging
#    server: 'https://kubernetes.default.svc'
#  project: knative-app
#  source:
#    path: staging
#    repoURL: https://github.com/marrober/quarkus-hello-world-deployment.git
#    targetRevision: main
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: quarkus-hello-world-production
#  namespace: openshift-gitops
#spec:
#  destination:
#    namespace: production
#    server: 'https://kubernetes.default.svc'
#  project: https://kubernetes.default.svc
#  source:
#    path: production
#    repoURL: https://github.com/marrober/quarkus-hello-world-deployment.git
#    targetRevision: main