apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: knative-app
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'development'
      server: '*'
    - namespace: 'staging'
      server: '*'
    - namespace: 'production'
      server: '*'
  sourceRepos:
    - '*'
  sourceNamespaces:
  - cicd
  - openshift-gitops