kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-development
  namespace: cicd
subjects:
- kind: ServiceAccount
  name: default
  namespace: development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
---
#kind: RoleBinding
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: knative-staging
#  namespace: cicd
#subjects:
#- kind: ServiceAccount
#  name: default
#  namespace: staging
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: 'system:image-puller'
---
#kind: RoleBinding
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: knative-production
#  namespace: cicd
#subjects:
#- kind: ServiceAccount
#  name: default
#  namespace: production
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: 'system:image-puller'