apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quarkus-hello-world
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
        - name: quarkus-hello-world
          livenessProbe:
            httpGet:
              path: /health/live
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /health/ready
            successThreshold: 1
          initialDelaySeconds: 60
  traffic:
